#noinst_LIBRARIES += src/iofwdutil/libiofwdutil.a


#src_iofwdutil_libiofwdutil_a_LIBLDFLAGS = \
#    @BOOST_LDFLAGS@ \
#    @BOOST_PROGRAM_OPTIONS_LIB@ \
#    @BOOST_DATE_TIME_LIB@ \
#    @BOOST_THREAD_LIB@ \
#    @BOOST_REGEX_LIB@

nobase_include_HEADERS +=  \
  src/iofwdutil/Configurable.hh \
  src/iofwdutil/LinkHelper.hh \
  src/iofwdutil/completion/BMICompletionID.hh \
  src/iofwdutil/completion/BMIResource.hh \
  src/iofwdutil/completion/BMISendID.hh \
  src/iofwdutil/completion/CompletionID.hh \
  src/iofwdutil/completion/CompositeCompletionID.hh \
  src/iofwdutil/completion/Context.hh \
  src/iofwdutil/completion/ContextBase.hh \
  src/iofwdutil/completion/IDAllocator.hh \
  src/iofwdutil/completion/Resource.hh \
  src/iofwdutil/completion/TimerCompletionID.hh \
  src/iofwdutil/completion/TimerResource.hh \
  src/iofwdutil/completion/Tracker.hh \
  src/iofwdutil/completion/WorkQueueCompletionID.hh \
  src/iofwdutil/zlog/ZLogTracer.hh \
  src/iofwdutil/zlog/LevelMatch.hh \
  src/iofwdutil/zlog/LevelParser.hh \
  src/iofwdutil/zlog/ZLog.hh \
  src/iofwdutil/zlog/ZLogConfigurator.hh \
  src/iofwdutil/zlog/ZLogDefaultFilter.hh \
  src/iofwdutil/zlog/ZLogException.hh \
  src/iofwdutil/zlog/ZLogFilter.hh \
  src/iofwdutil/zlog/ZLogSink.hh \
  src/iofwdutil/zlog/ZLogSinkFile.hh \
  src/iofwdutil/zlog/ZLogSinkStd.hh \
  src/iofwdutil/zlog/ZLogSinkStdErr.hh \
  src/iofwdutil/zlog/ZLogSinkStdOut.hh \
  src/iofwdutil/zlog/ZLogSource.hh \
  src/iofwdutil/bmi/BMI.hh \
  src/iofwdutil/bmi/BMIAddr.hh \
  src/iofwdutil/bmi/BMIBuffer.hh \
  src/iofwdutil/bmi/BMIError.hh \
  src/iofwdutil/bmi/BMIException.hh \
  src/iofwdutil/bmi/BMITag.hh \
  src/iofwdutil/bmi/BMIUnexpectedBuffer.hh \
  src/iofwdutil/workqueue/CompletionTracker.hh \
  src/iofwdutil/workqueue/Future.hh \
  src/iofwdutil/workqueue/PoolWorkQueue.hh \
  src/iofwdutil/workqueue/SynchronousWorkQueue.hh \
  src/iofwdutil/workqueue/WorkItem.hh \
  src/iofwdutil/workqueue/WorkQueue.hh \
  src/iofwdutil/workqueue/WorkQueueBase.hh \
  src/iofwdutil/ConfigException.hh \
  src/iofwdutil/ConfigContainer.hh \
  src/iofwdutil/ConfigFile.hh \
  src/iofwdutil/HybridAllocator.hh \
  src/iofwdutil/IOFWDLog.hh \
  src/iofwdutil/IOFWDLog-fwd.hh \
  src/iofwdutil/IntrusiveHelper.hh \
  src/iofwdutil/Singleton.hh \
  src/iofwdutil/TimeVal.hh \
  src/iofwdutil/Timer.hh \
  src/iofwdutil/ZException.hh \
  src/iofwdutil/always_assert.hh \
  src/iofwdutil/assert.hh \
  src/iofwdutil/backtrace.hh \
  src/iofwdutil/demangle.hh \
  src/iofwdutil/signals.hh \
  src/iofwdutil/tools.hh \
  src/iofwdutil/typestorage.hh \
  src/iofwdutil/IOFWDLogException.hh \
  src/iofwdutil/boost-spirit.hh \
  src/iofwdutil/PerfCounters.hh \
  src/iofwdutil/ThreadPool.hh \
  src/iofwdutil/InjectPool.hh \
  src/iofwdutil/hash/HashFactory.hh\
  src/iofwdutil/hash/HashFunc.hh\
  src/iofwdutil/hash/HashException.hh\
  src/iofwdutil/hash/SHA1Simple.hh\
  src/iofwdutil/hash/CRC64.hh \
  src/iofwdutil/hash/NoneHash.hh \
  src/iofwdutil/hash/HashAutoRegister.hh\
  src/iofwdutil/Factory.hh \
  src/iofwdutil/FactoryClient.hh \
  src/iofwdutil/FactoryAutoRegister.hh \
  src/iofwdutil/CreateMethod.hh \
  src/iofwdutil/FactoryException.hh \
  src/iofwdutil/FactoryHelper.hh \
  src/iofwdutil/atomics.hh \
  src/iofwdutil/rm/IntervalMergeTree.hh \
  src/iofwdutil/mm/IOFWDMemoryManager.hh \
  src/iofwdutil/mm/BMIMemoryManager.hh \
  src/iofwdutil/transform/GenericTransform.hh \
  src/iofwdutil/transform/TransformException.hh \
  src/iofwdutil/transform/LZFDecompress.hh \
  src/iofwdutil/transform/LZFCompress.hh \
  src/iofwdutil/transform/CopyTransform.hh \
  src/iofwdutil/transform/IOReadBuffer.hh \
  src/iofwdutil/transform/IOWriteBuffer.hh \
  src/iofwdutil/transform/BlockingCompress.hh \
  src/iofwdutil/transform/BlockingDecompress.hh \
  src/iofwdutil/transform/BlockingCommon.hh \
  src/iofwdutil/ExceptionBacktrace.hh \
  src/iofwdutil/IofwdutilLinkHelper.hh \
  src/iofwdutil/hash/Adler32.hh \
  src/iofwdutil/hash/CRC32.hh \
  src/iofwdutil/transform/ZLibBase.hh \
  src/iofwdutil/transform/ZLibCompress.hh \
  src/iofwdutil/transform/ZLibDecompress.hh \
  src/iofwdutil/transform/BZLib.hh \
  src/iofwdutil/transform/BZCompress.hh \
  src/iofwdutil/transform/BZDecompress.hh \
  src/iofwdutil/hash/OpenSSLHash.hh \
  src/iofwdutil/hash/OpenSSLException.hh \
  src/iofwdutil/hash/OpenSSLInit.hh \
  src/iofwdutil/transform/LZOCompress.hh \
  src/iofwdutil/transform/LZODecompress.hh \
  src/iofwdutil/transform/LZOCommon.hh \
  src/iofwdutil/transform/LZOException.hh 


lib_libiofslcommon_a_SOURCES += \
src/iofwdutil/Configurable.hh \
src/iofwdutil/Configurable.cpp \
src/iofwdutil/LinkHelper.hh \
src/iofwdutil/completion/BMICompletionID.hh \
src/iofwdutil/completion/BMIResource.hh \
src/iofwdutil/completion/BMISendID.hh \
src/iofwdutil/completion/CompletionID.hh \
src/iofwdutil/completion/CompositeCompletionID.hh \
src/iofwdutil/completion/Context.hh \
src/iofwdutil/completion/ContextBase.hh \
src/iofwdutil/completion/IDAllocator.hh \
src/iofwdutil/completion/Resource.hh \
src/iofwdutil/completion/TimerCompletionID.hh \
src/iofwdutil/completion/TimerResource.hh \
src/iofwdutil/completion/Tracker.hh \
src/iofwdutil/completion/WorkQueueCompletionID.hh \
src/iofwdutil/completion/BMICompletionID.cpp \
src/iofwdutil/completion/BMIResource.cpp \
src/iofwdutil/completion/CompletionID.cpp \
src/iofwdutil/completion/CompositeCompletionID.cpp \
src/iofwdutil/completion/ContextBase.cpp \
src/iofwdutil/completion/Resource.cpp \
src/iofwdutil/completion/TimerResource.cpp \
src/iofwdutil/completion/Tracker.cpp \
src/iofwdutil/completion/WorkQueueCompletionID.cpp \
 \
src/iofwdutil/zlog/ZLogTracer.hh \
src/iofwdutil/zlog/ZLogTracer.cpp \
src/iofwdutil/zlog/LevelMatch.cpp \
src/iofwdutil/zlog/LevelParser.cpp \
src/iofwdutil/zlog/ZLog.cpp \
src/iofwdutil/zlog/ZLogConfigurator.cpp \
src/iofwdutil/zlog/ZLogDefaultFilter.cpp \
src/iofwdutil/zlog/ZLogFilter.cpp \
src/iofwdutil/zlog/ZLogSink.cpp \
src/iofwdutil/zlog/ZLogSinkFile.cpp \
src/iofwdutil/zlog/ZLogSinkStd.cpp \
src/iofwdutil/zlog/ZLogSinkStdErr.cpp \
src/iofwdutil/zlog/ZLogSinkStdOut.cpp \
src/iofwdutil/zlog/ZLogSource.cpp \
src/iofwdutil/zlog/LevelMatch.hh \
src/iofwdutil/zlog/LevelParser.hh \
src/iofwdutil/zlog/ZLog.hh \
src/iofwdutil/zlog/ZLogConfigurator.hh \
src/iofwdutil/zlog/ZLogDefaultFilter.hh \
src/iofwdutil/zlog/ZLogException.hh \
src/iofwdutil/zlog/ZLogFilter.hh \
src/iofwdutil/zlog/ZLogSink.hh \
src/iofwdutil/zlog/ZLogSinkFile.hh \
src/iofwdutil/zlog/ZLogSinkStd.hh \
src/iofwdutil/zlog/ZLogSinkStdErr.hh \
src/iofwdutil/zlog/ZLogSinkStdOut.hh \
src/iofwdutil/zlog/ZLogSource.hh \
 \
src/iofwdutil/bmi/BMI.cpp \
src/iofwdutil/bmi/BMIAddr.cpp \
src/iofwdutil/bmi/BMIBuffer.cpp \
src/iofwdutil/bmi/BMIError.cpp \
src/iofwdutil/bmi/BMIException.cpp \
src/iofwdutil/bmi/BMIUnexpectedBuffer.cpp \
src/iofwdutil/bmi/BMI.hh \
src/iofwdutil/bmi/BMIAddr.hh \
src/iofwdutil/bmi/BMIBuffer.hh \
src/iofwdutil/bmi/BMIError.hh \
src/iofwdutil/bmi/BMIException.hh \
src/iofwdutil/bmi/BMITag.hh \
src/iofwdutil/bmi/BMIUnexpectedBuffer.hh \
 \
src/iofwdutil/workqueue/CompletionTracker.cpp \
src/iofwdutil/workqueue/PoolWorkQueue.cpp \
src/iofwdutil/workqueue/SynchronousWorkQueue.cpp \
src/iofwdutil/workqueue/WorkItem.cpp \
src/iofwdutil/workqueue/WorkQueue.cpp \
src/iofwdutil/workqueue/WorkQueueBase.cpp \
src/iofwdutil/workqueue/CompletionTracker.hh \
src/iofwdutil/workqueue/Future.hh \
src/iofwdutil/workqueue/PoolWorkQueue.hh \
src/iofwdutil/workqueue/SynchronousWorkQueue.hh \
src/iofwdutil/workqueue/WorkItem.hh \
src/iofwdutil/workqueue/WorkQueue.hh \
src/iofwdutil/workqueue/WorkQueueBase.hh \
 \
src/iofwdutil/ConfigException.hh \
src/iofwdutil/ConfigException.cpp \
src/iofwdutil/ConfigContainer.hh \
src/iofwdutil/ConfigFile.hh \
src/iofwdutil/HybridAllocator.hh \
src/iofwdutil/IOFWDLog.hh \
src/iofwdutil/IOFWDLog-fwd.hh \
src/iofwdutil/IntrusiveHelper.hh \
src/iofwdutil/Singleton.hh \
src/iofwdutil/TimeVal.hh \
src/iofwdutil/Timer.hh \
src/iofwdutil/ZException.hh \
src/iofwdutil/always_assert.hh \
src/iofwdutil/assert.hh \
src/iofwdutil/backtrace.hh \
src/iofwdutil/demangle.hh \
src/iofwdutil/signals.hh \
src/iofwdutil/tools.hh \
src/iofwdutil/typestorage.hh \
src/iofwdutil/ConfigContainer.cpp \
src/iofwdutil/ConfigFile.cpp \
src/iofwdutil/IOFWDLog.cpp \
src/iofwdutil/IOFWDLogException.hh \
src/iofwdutil/TimeVal.cpp \
src/iofwdutil/Timer.cpp \
src/iofwdutil/ZException.cpp \
src/iofwdutil/always_assert.cpp \
src/iofwdutil/backtrace.cpp \
src/iofwdutil/demangle.cpp \
src/iofwdutil/signals.cpp \
src/iofwdutil/boost-spirit.hh \
src/iofwdutil/PerfCounters.hh \
src/iofwdutil/PerfCounters.cpp \
src/iofwdutil/ThreadPool.hh \
src/iofwdutil/ThreadPool.cpp \
src/iofwdutil/InjectPool.hh \
\
src/iofwdutil/hash/HashFactory.cpp\
src/iofwdutil/hash/HashFactory.hh\
src/iofwdutil/hash/HashFunc.cpp\
src/iofwdutil/hash/HashFunc.hh\
src/iofwdutil/hash/HashException.hh\
src/iofwdutil/hash/SHA1Simple.cpp\
src/iofwdutil/hash/SHA1Simple.hh\
src/iofwdutil/hash/CRC64.hh \
src/iofwdutil/hash/CRC64.cpp \
src/iofwdutil/hash/NoneHash.hh \
src/iofwdutil/hash/NoneHash.cpp \
src/iofwdutil/hash/HashAutoRegister.hh\
\
src/iofwdutil/Factory.hh \
src/iofwdutil/FactoryClient.hh \
src/iofwdutil/FactoryAutoRegister.hh \
src/iofwdutil/CreateMethod.hh \
src/iofwdutil/FactoryException.hh \
src/iofwdutil/FactoryHelper.hh \
\
src/iofwdutil/atomics.hh \
\
src/iofwdutil/rm/IntervalMergeTree.hh \
src/iofwdutil/rm/IntervalMergeTree.cpp \
\
src/iofwdutil/mm/IOFWDMemoryManager.hh \
src/iofwdutil/mm/BMIMemoryManager.hh \
src/iofwdutil/mm/BMIMemoryManager.cpp \
\
src/iofwdutil/transform/GenericTransform.hh \
src/iofwdutil/transform/GenericTransform.cpp \
src/iofwdutil/transform/TransformException.hh \
src/iofwdutil/transform/LZFDecompress.cpp \
src/iofwdutil/transform/LZFDecompress.hh \
src/iofwdutil/transform/LZFCompress.hh \
src/iofwdutil/transform/LZFCompress.cpp \
src/iofwdutil/transform/CopyTransform.cpp \
src/iofwdutil/transform/CopyTransform.hh \
src/iofwdutil/transform/IOReadBuffer.cpp \
src/iofwdutil/transform/IOReadBuffer.hh \
src/iofwdutil/transform/IOWriteBuffer.cpp \
src/iofwdutil/transform/IOWriteBuffer.hh \
src/iofwdutil/transform/BlockingCompress.hh \
src/iofwdutil/transform/BlockingCompress.cpp \
src/iofwdutil/transform/BlockingDecompress.hh \
src/iofwdutil/transform/BlockingDecompress.cpp \
src/iofwdutil/transform/BlockingCommon.hh \
\
src/iofwdutil/stats/CounterHelper.hh \
src/iofwdutil/stats/BaseCounter.hh \
src/iofwdutil/stats/SingleCounter.hh \
src/iofwdutil/stats/CounterWindow.hh \
src/iofwdutil/stats/CounterConfig.hh \
src/iofwdutil/stats/ByteCounter.hh \
src/iofwdutil/stats/ByteCounterWindow.hh \
src/iofwdutil/stats/CounterTable.cpp \
src/iofwdutil/stats/CounterTable.hh \
src/iofwdutil/stats/DoublePrecisionCounter.hh \
src/iofwdutil/stats/DoublePrecisionCounterWindow.hh \
src/iofwdutil/stats/IncCounter.hh \
src/iofwdutil/stats/TimeCounter.hh \
src/iofwdutil/stats/TimeCounterWindow.hh \
src/iofwdutil/stats/AutoCounter.hh \
src/iofwdutil/stats/ScopedCounter.hh \
src/iofwdutil/stats/ScopedTimer.hh \
\
src/iofwdutil/ExceptionBacktrace.hh \
src/iofwdutil/ExceptionBacktrace.cpp \
src/iofwdutil/IofwdutilLinkHelper.hh \
src/iofwdutil/IofwdutilLinkHelper.cpp

if HAVE_ZLIB
lib_libiofslcommon_a_SOURCES += \
src/iofwdutil/hash/Adler32.hh \
src/iofwdutil/hash/Adler32.cpp \
src/iofwdutil/hash/CRC32.hh \
src/iofwdutil/hash/CRC32.cpp \
src/iofwdutil/transform/ZLibBase.hh \
src/iofwdutil/transform/ZLibBase.cpp \
src/iofwdutil/transform/ZLibCompress.hh \
src/iofwdutil/transform/ZLibCompress.cpp \
src/iofwdutil/transform/ZLibDecompress.hh \
src/iofwdutil/transform/ZLibDecompress.cpp
endif

if HAVE_BZLIB
lib_libiofslcommon_a_SOURCES += \
src/iofwdutil/transform/BZLib.hh \
src/iofwdutil/transform/BZLib.cpp \
src/iofwdutil/transform/BZCompress.hh \
src/iofwdutil/transform/BZCompress.cpp \
src/iofwdutil/transform/BZDecompress.hh \
src/iofwdutil/transform/BZDecompress.cpp
endif

if HAVE_OPENSSL
lib_libiofslcommon_a_SOURCES += \
	src/iofwdutil/hash/OpenSSLHash.hh \
	src/iofwdutil/hash/OpenSSLException.hh \
	src/iofwdutil/hash/OpenSSLHash.cpp \
	src/iofwdutil/hash/OpenSSLInit.hh \
	src/iofwdutil/hash/OpenSSLInit.cpp
endif


if HAVE_LZO
lib_libiofslcommon_a_SOURCES += \
	src/iofwdutil/transform/LZOCompress.hh \
	src/iofwdutil/transform/LZODecompress.hh \
	src/iofwdutil/transform/LZOCompress.cpp \
	src/iofwdutil/transform/LZODecompress.cpp \
	src/iofwdutil/transform/LZOCommon.hh \
	src/iofwdutil/transform/LZOCommon.cpp \
	src/iofwdutil/transform/LZOException.hh \
	src/iofwdutil/transform/LZOException.cpp
endif
