noinst_LIBRARIES += src/iofwdutil/libiofwdutil.a


src_iofwdutil_libiofwdutil_a_LIBLDFLAGS = \
    @BOOST_LDFLAGS@ \
    @BOOST_PROGRAM_OPTIONS_LIB@ \
    @BOOST_DATE_TIME_LIB@ \
    @BOOST_THREAD_LIB@ \
    @BOOST_REGEX_LIB@


src_iofwdutil_libiofwdutil_a_SOURCES = \
src/iofwdutil/Configurable.hh \
src/iofwdutil/Configurable.cpp \
src/iofwdutil/LinkHelper.hh \
src/iofwdutil/completion/BMICompletionID.hh \
src/iofwdutil/completion/BMIResource.hh \
src/iofwdutil/completion/BMISendID.hh \
src/iofwdutil/completion/CompletionID.hh \
src/iofwdutil/completion/CompositeCompletionID.hh \
src/iofwdutil/completion/Context.hh \
src/iofwdutil/completion/ContextBase.hh \
src/iofwdutil/completion/IDAllocator.hh \
src/iofwdutil/completion/Resource.hh \
src/iofwdutil/completion/TimerCompletionID.hh \
src/iofwdutil/completion/TimerResource.hh \
src/iofwdutil/completion/Tracker.hh \
src/iofwdutil/completion/WorkQueueCompletionID.hh \
src/iofwdutil/completion/BMICompletionID.cpp \
src/iofwdutil/completion/BMIResource.cpp \
src/iofwdutil/completion/CompletionID.cpp \
src/iofwdutil/completion/CompositeCompletionID.cpp \
src/iofwdutil/completion/ContextBase.cpp \
src/iofwdutil/completion/Resource.cpp \
src/iofwdutil/completion/TimerResource.cpp \
src/iofwdutil/completion/Tracker.cpp \
src/iofwdutil/completion/WorkQueueCompletionID.cpp \
 \
src/iofwdutil/zlog/LevelMatch.cpp \
src/iofwdutil/zlog/LevelParser.cpp \
src/iofwdutil/zlog/ZLog.cpp \
src/iofwdutil/zlog/ZLogConfigurator.cpp \
src/iofwdutil/zlog/ZLogDefaultFilter.cpp \
src/iofwdutil/zlog/ZLogFilter.cpp \
src/iofwdutil/zlog/ZLogSink.cpp \
src/iofwdutil/zlog/ZLogSinkFile.cpp \
src/iofwdutil/zlog/ZLogSinkStd.cpp \
src/iofwdutil/zlog/ZLogSinkStdErr.cpp \
src/iofwdutil/zlog/ZLogSinkStdOut.cpp \
src/iofwdutil/zlog/ZLogSource.cpp \
src/iofwdutil/zlog/LevelMatch.hh \
src/iofwdutil/zlog/LevelParser.hh \
src/iofwdutil/zlog/ZLog.hh \
src/iofwdutil/zlog/ZLogConfigurator.hh \
src/iofwdutil/zlog/ZLogDefaultFilter.hh \
src/iofwdutil/zlog/ZLogException.hh \
src/iofwdutil/zlog/ZLogFilter.hh \
src/iofwdutil/zlog/ZLogSink.hh \
src/iofwdutil/zlog/ZLogSinkFile.hh \
src/iofwdutil/zlog/ZLogSinkStd.hh \
src/iofwdutil/zlog/ZLogSinkStdErr.hh \
src/iofwdutil/zlog/ZLogSinkStdOut.hh \
src/iofwdutil/zlog/ZLogSource.hh \
 \
src/iofwdutil/bmi/BMI.cpp \
src/iofwdutil/bmi/BMIAddr.cpp \
src/iofwdutil/bmi/BMIBuffer.cpp \
src/iofwdutil/bmi/BMIContext.cpp \
src/iofwdutil/bmi/BMIError.cpp \
src/iofwdutil/bmi/BMIException.cpp \
src/iofwdutil/bmi/BMIUnexpectedBuffer.cpp \
src/iofwdutil/bmi/BMI.hh \
src/iofwdutil/bmi/BMIAddr.hh \
src/iofwdutil/bmi/BMIBuffer.hh \
src/iofwdutil/bmi/BMIContext.hh \
src/iofwdutil/bmi/BMIError.hh \
src/iofwdutil/bmi/BMIException.hh \
src/iofwdutil/bmi/BMIOp.hh \
src/iofwdutil/bmi/BMITag.hh \
src/iofwdutil/bmi/BMIUnexpectedBuffer.hh \
 \
src/iofwdutil/zconfig/ConfigParser.hh \
src/iofwdutil/zconfig/ConfigParser.cpp \
 \
src/iofwdutil/workqueue/CompletionTracker.cpp \
src/iofwdutil/workqueue/PoolWorkQueue.cpp \
src/iofwdutil/workqueue/SynchronousWorkQueue.cpp \
src/iofwdutil/workqueue/WorkItem.cpp \
src/iofwdutil/workqueue/WorkQueue.cpp \
src/iofwdutil/workqueue/WorkQueueBase.cpp \
src/iofwdutil/workqueue/CompletionTracker.hh \
src/iofwdutil/workqueue/Future.hh \
src/iofwdutil/workqueue/PoolWorkQueue.hh \
src/iofwdutil/workqueue/SynchronousWorkQueue.hh \
src/iofwdutil/workqueue/WorkItem.hh \
src/iofwdutil/workqueue/WorkQueue.hh \
src/iofwdutil/workqueue/WorkQueueBase.hh \
 \
src/iofwdutil/CFKeyMissingException.hh \
src/iofwdutil/ConfigContainer.hh \
src/iofwdutil/ConfigFile.hh \
src/iofwdutil/HybridAllocator.hh \
src/iofwdutil/IOFWDLog.hh \
src/iofwdutil/IOFWDLog-fwd.hh \
src/iofwdutil/IntrusiveHelper.hh \
src/iofwdutil/Singleton.hh \
src/iofwdutil/TimeVal.hh \
src/iofwdutil/Timer.hh \
src/iofwdutil/ZException.hh \
src/iofwdutil/always_assert.hh \
src/iofwdutil/assert.hh \
src/iofwdutil/backtrace.hh \
src/iofwdutil/demangle.hh \
src/iofwdutil/signals.hh \
src/iofwdutil/tools.hh \
src/iofwdutil/typestorage.hh \
src/iofwdutil/CFKeyMissingException.cpp \
src/iofwdutil/ConfigContainer.cpp \
src/iofwdutil/ConfigFile.cpp \
src/iofwdutil/IOFWDLog.cpp \
src/iofwdutil/TimeVal.cpp \
src/iofwdutil/Timer.cpp \
src/iofwdutil/ZException.cpp \
src/iofwdutil/always_assert.cpp \
src/iofwdutil/backtrace.cpp \
src/iofwdutil/demangle.cpp \
src/iofwdutil/signals.cpp \
src/iofwdutil/boost-spirit.hh \
src/iofwdutil/PerfCounters.hh \
src/iofwdutil/PerfCounters.cpp \
src/iofwdutil/ThreadPool.hh \
src/iofwdutil/ThreadPool.cpp \
src/iofwdutil/InjectPool.hh \
\
src/iofwdutil/Factory.hh \
src/iofwdutil/FactoryAutoRegister.hh \
src/iofwdutil/CreateMethod.hh \
src/iofwdutil/FactoryException.hh \
src/iofwdutil/FactoryHelper.hh \
\
src/iofwdutil/atomics.hh \
\
src/iofwdutil/rm/IntervalMergeTree.hh \
src/iofwdutil/rm/IntervalMergeTree.cpp \
\
src/iofwdutil/mm/IOFWDMemoryManager.hh \
src/iofwdutil/mm/BMIMemoryManager.hh \
src/iofwdutil/mm/BMIMemoryManager.cpp
