#
# unit tests build rules
#
if HAVE_CUNIT

test_unit_tests_ldadd =          \
	src/zoidfs/libzoidfs-util.a  \
	src/iofwdutil/libiofwdutil.a \
	src/c-util/libc-util.a       \
    @CUNIT_LIBS@                 \
    @ZFS_DISPATCHER_LIBS@

test_unit_tests_ldflags =        \
    @CUNIT_LDFLAGS@              \
    @ZFS_DISPATCHER_LDFLAGS@

test_unit_tests_cflags =         \
    -I./src/zoidfs               \
    -I./src/c-util               \
    @CUNIT_CFLAGS@               \
    @ZFS_DISPATCHER_CFLAGS@

bin_PROGRAMS += test/unit-tests/zoidfs-md-cunit test/unit-tests/zoidfs-md-cunit-local test/unit-tests/zoidfs-io-cunit \
test/unit-tests/zoidfs-io-cunit-local

test_unit_tests_zoidfs_md_cunit_SOURCES = test/unit-tests/zoidfs-md-cunit.c
test_unit_tests_zoidfs_md_cunit_LDADD = ${test_unit_tests_ldadd} src/zoidfs/libzoidfsclient.a
test_unit_tests_zoidfs_md_cunit_LDFLAGS = ${test_unit_tests_ldflags}
test_unit_tests_zoidfs_md_cunit_CFLAGS = ${test_unit_tests_cflags}
 
test_unit_tests_zoidfs_md_cunit_local_SOURCES = test/unit-tests/zoidfs-md-cunit.c
test_unit_tests_zoidfs_md_cunit_local_LDADD = src/zoidfs/libzoidfs.a ${test_unit_tests_ldadd}
test_unit_tests_zoidfs_md_cunit_local_LDFLAGS = ${test_unit_tests_ldflags}
test_unit_tests_zoidfs_md_cunit_local_CFLAGS = ${test_unit_tests_cflags}

test_unit_tests_zoidfs_io_cunit_SOURCES = test/unit-tests/zoidfs-io-cunit.c
test_unit_tests_zoidfs_io_cunit_LDADD = ${test_unit_tests_ldadd} src/zoidfs/libzoidfsclient.a
test_unit_tests_zoidfs_io_cunit_LDFLAGS = ${test_unit_tests_ldflags}
test_unit_tests_zoidfs_io_cunit_CFLAGS = ${test_unit_tests_cflags}
 
test_unit_tests_zoidfs_io_cunit_local_SOURCES = test/unit-tests/zoidfs-io-cunit.c
test_unit_tests_zoidfs_io_cunit_local_LDADD = src/zoidfs/libzoidfs.a ${test_unit_tests_ldadd}
test_unit_tests_zoidfs_io_cunit_local_LDFLAGS = ${test_unit_tests_ldflags}
test_unit_tests_zoidfs_io_cunit_local_CFLAGS = ${test_unit_tests_cflags}
endif

#
# microbenchmark build rules
#
if HAVE_MPI

test_microbenchmarks_ldadd =     \
    -lm                          \
    src/zoidfs/libzoidfs-util.a  \
    src/iofwdutil/libiofwdutil.a \
    src/c-util/libc-util.a       \
    @ZFS_DISPATCHER_LIBS@

test_microbenchmarks_ldflags =   \
    @ZFS_DISPATCHER_LDFLAGS@

test_microbenchmarks_cflags =    \
    -I./src/zoidfs               \
    -I./src/c-util               \
    @ZFS_DISPATCHER_CFLAGS@

bin_PROGRAMS += test/zoidfs-microbenchmarks/creat-thput test/zoidfs-microbenchmarks/creat-thput-local \
test/zoidfs-microbenchmarks/mkdir-thput test/zoidfs-microbenchmarks/mkdir-thput-local test/zoidfs-microbenchmarks/lookup-thput \
test/zoidfs-microbenchmarks/lookup-thput-local test/zoidfs-microbenchmarks/getattr-thput test/zoidfs-microbenchmarks/getattr-thput-local \
test/zoidfs-microbenchmarks/setattr-thput test/zoidfs-microbenchmarks/setattr-thput-local test/zoidfs-microbenchmarks/remove-thput \
test/zoidfs-microbenchmarks/remove-thput-local test/zoidfs-microbenchmarks/null-thput test/zoidfs-microbenchmarks/null-thput-local

test_zoidfs_microbenchmarks_creat_thput_SOURCES = test/zoidfs-microbenchmarks/creat-thput.c
test_zoidfs_microbenchmarks_creat_thput_LDADD = ${test_microbenchmarks_ldadd} src/zoidfs/libzoidfsclient.a
test_zoidfs_microbenchmarks_creat_thput_LDFLAGS = ${test_microbenchmarks_ldflags}
test_zoidfs_microbenchmarks_creat_thput_CFLAGS = ${test_microbenchmarks_cflags}
 
test_zoidfs_microbenchmarks_creat_thput_local_SOURCES = test/zoidfs-microbenchmarks/creat-thput.c
test_zoidfs_microbenchmarks_creat_thput_local_LDADD = src/zoidfs/libzoidfs.a ${test_microbenchmarks_ldadd}
test_zoidfs_microbenchmarks_creat_thput_local_LDFLAGS = ${test_microbenchmarks_ldflags}
test_zoidfs_microbenchmarks_creat_thput_local_CFLAGS = ${test_microbenchmarks_cflags}
 
test_zoidfs_microbenchmarks_null_thput_SOURCES = test/zoidfs-microbenchmarks/null-thput.c
test_zoidfs_microbenchmarks_null_thput_LDADD = ${test_microbenchmarks_ldadd} src/zoidfs/libzoidfsclient.a
test_zoidfs_microbenchmarks_null_thput_LDFLAGS = ${test_microbenchmarks_ldflags}
test_zoidfs_microbenchmarks_null_thput_CFLAGS = ${test_microbenchmarks_cflags}
 
test_zoidfs_microbenchmarks_null_thput_local_SOURCES = test/zoidfs-microbenchmarks/null-thput.c
test_zoidfs_microbenchmarks_null_thput_local_LDADD = src/zoidfs/libzoidfs.a ${test_microbenchmarks_ldadd}
test_zoidfs_microbenchmarks_null_thput_local_LDFLAGS = ${test_microbenchmarks_ldflags}
test_zoidfs_microbenchmarks_null_thput_local_CFLAGS = ${test_microbenchmarks_cflags}
 
test_zoidfs_microbenchmarks_remove_thput_SOURCES = test/zoidfs-microbenchmarks/remove-thput.c
test_zoidfs_microbenchmarks_remove_thput_LDADD = ${test_microbenchmarks_ldadd} src/zoidfs/libzoidfsclient.a
test_zoidfs_microbenchmarks_remove_thput_LDFLAGS = ${test_microbenchmarks_ldflags}
test_zoidfs_microbenchmarks_remove_thput_CFLAGS = ${test_microbenchmarks_cflags}
 
test_zoidfs_microbenchmarks_remove_thput_local_SOURCES = test/zoidfs-microbenchmarks/remove-thput.c
test_zoidfs_microbenchmarks_remove_thput_local_LDADD = src/zoidfs/libzoidfs.a ${test_microbenchmarks_ldadd}
test_zoidfs_microbenchmarks_remove_thput_local_LDFLAGS = ${test_microbenchmarks_ldflags}
test_zoidfs_microbenchmarks_remove_thput_local_CFLAGS = ${test_microbenchmarks_cflags}
 
test_zoidfs_microbenchmarks_lookup_thput_SOURCES = test/zoidfs-microbenchmarks/lookup-thput.c
test_zoidfs_microbenchmarks_lookup_thput_LDADD = ${test_microbenchmarks_ldadd} src/zoidfs/libzoidfsclient.a
test_zoidfs_microbenchmarks_lookup_thput_LDFLAGS = ${test_microbenchmarks_ldflags}
test_zoidfs_microbenchmarks_lookup_thput_CFLAGS = ${test_microbenchmarks_cflags}
 
test_zoidfs_microbenchmarks_lookup_thput_local_SOURCES = test/zoidfs-microbenchmarks/lookup-thput.c
test_zoidfs_microbenchmarks_lookup_thput_local_LDADD = src/zoidfs/libzoidfs.a ${test_microbenchmarks_ldadd}
test_zoidfs_microbenchmarks_lookup_thput_local_LDFLAGS = ${test_microbenchmarks_ldflags}
test_zoidfs_microbenchmarks_lookup_thput_local_CFLAGS = ${test_microbenchmarks_cflags}
 
test_zoidfs_microbenchmarks_getattr_thput_SOURCES = test/zoidfs-microbenchmarks/getattr-thput.c
test_zoidfs_microbenchmarks_getattr_thput_LDADD = ${test_microbenchmarks_ldadd} src/zoidfs/libzoidfsclient.a
test_zoidfs_microbenchmarks_getattr_thput_LDFLAGS = ${test_microbenchmarks_ldflags}
test_zoidfs_microbenchmarks_getattr_thput_CFLAGS = ${test_microbenchmarks_cflags}
 
test_zoidfs_microbenchmarks_getattr_thput_local_SOURCES = test/zoidfs-microbenchmarks/getattr-thput.c
test_zoidfs_microbenchmarks_getattr_thput_local_LDADD = src/zoidfs/libzoidfs.a ${test_microbenchmarks_ldadd}
test_zoidfs_microbenchmarks_getattr_thput_local_LDFLAGS = ${test_microbenchmarks_ldflags}
test_zoidfs_microbenchmarks_getattr_thput_local_CFLAGS = ${test_microbenchmarks_cflags}
 
test_zoidfs_microbenchmarks_setattr_thput_SOURCES = test/zoidfs-microbenchmarks/setattr-thput.c
test_zoidfs_microbenchmarks_setattr_thput_LDADD = ${test_microbenchmarks_ldadd} src/zoidfs/libzoidfsclient.a
test_zoidfs_microbenchmarks_setattr_thput_LDFLAGS = ${test_microbenchmarks_ldflags}
test_zoidfs_microbenchmarks_setattr_thput_CFLAGS = ${test_microbenchmarks_cflags}
 
test_zoidfs_microbenchmarks_setattr_thput_local_SOURCES = test/zoidfs-microbenchmarks/setattr-thput.c
test_zoidfs_microbenchmarks_setattr_thput_local_LDADD = src/zoidfs/libzoidfs.a ${test_microbenchmarks_ldadd}
test_zoidfs_microbenchmarks_setattr_thput_local_LDFLAGS = ${test_microbenchmarks_ldflags}
test_zoidfs_microbenchmarks_setattr_thput_local_CFLAGS = ${test_microbenchmarks_cflags}
 
test_zoidfs_microbenchmarks_mkdir_thput_SOURCES = test/zoidfs-microbenchmarks/mkdir-thput.c
test_zoidfs_microbenchmarks_mkdir_thput_LDADD = ${test_microbenchmarks_ldadd} src/zoidfs/libzoidfsclient.a
test_zoidfs_microbenchmarks_mkdir_thput_LDFLAGS = ${test_microbenchmarks_ldflags}
test_zoidfs_microbenchmarks_mkdir_thput_CFLAGS = ${test_microbenchmarks_cflags}
 
test_zoidfs_microbenchmarks_mkdir_thput_local_SOURCES = test/zoidfs-microbenchmarks/mkdir-thput.c
test_zoidfs_microbenchmarks_mkdir_thput_local_LDADD = src/zoidfs/libzoidfs.a ${test_microbenchmarks_ldadd}
test_zoidfs_microbenchmarks_mkdir_thput_local_LDFLAGS = ${test_microbenchmarks_ldflags}
test_zoidfs_microbenchmarks_mkdir_thput_local_CFLAGS = ${test_microbenchmarks_cflags}
endif
