
sandbox_ldflags = $(AM_LDFLAGS) \
    @BOOST_LDFLAGS@ \
    @BOOST_PROGRAM_OPTIONS_LIB@ \
    @BOOST_DATE_TIME_LIB@ \
    @BOOST_THREAD_LIB@ \
    @BOOST_REGEX_LIB@

noinst_PROGRAMS += sandbox/recordparam
sandbox_recordparam_SOURCES = sandbox/recordparam.cpp
sandbox_recordparam_LDFLAGS = $(sandbox_ldflags)

noinst_PROGRAMS += sandbox/regex
sandbox_regex_SOURCES = sandbox/regex.cpp
sandbox_regex_LDFLAGS = $(sandbox_ldflags) 


