dnl
dnl
dnl Try to found glib atomic int functions.
dnl  sets GLIB_OK to 1 if found.
dnl  Also sets GLIB_LDFLAGS, _LIBS, _CFLAGS, _CPPFLAGS
dnl
AC_DEFUN([AX_GLIB],
[
GLIB_LDFLAGS=
GLIB_CFLAGS=
GLIB_LIBS=
GLIB_CPPFLAGS=
GLIB_OK=
AC_REQUIRE([PKG_PROG_PKG_CONFIG])
PKG_CHECK_MODULES([GLIB], [glib-2.0 >= 2.10], [GLIB_OK=1], [GLIB_OK=])
AC_SUBST([GLIB_OK])
AC_SUBST([GLIB_LDFLAGS])
AC_SUBST([GLIB_CFLAGS])
AC_SUBST([GLIB_CPPFLAGS])
AC_SUBST([GLIB_LIBS])
])
