SERVERSOURCES += \
src/iofwd/extraservice/aarpc/AtomicAppendServerRPC.hh \
src/iofwd/extraservice/aarpc/AtomicAppendServerRPC.cpp \
src/iofwd/extraservice/aarpc/AtomicAppendClientRPC.hh \
src/iofwd/extraservice/aarpc/AtomicAppendClientRPC.cpp
