

if HAVE_FTB
include src/iofwd/extraservice/ftb/Makefile.subdir
endif


include src/iofwd/extraservice/rpctest/Makefile.subdir

# clientrpc service
include src/iofwd/extraservice/iofslclientrpc/Makefile.subdir

