

if HAVE_FTB
include src/iofwd/extraservice/ftb/Makefile.subdir
endif

include src/iofwd/extraservice/rpctest/Makefile.subdir
include src/iofwd/extraservice/aarpc/Makefile.subdir
include src/iofwd/extraservice/sfp/Makefile.subdir

