if BUILD_IOFWD_CLIENT

ZOIDFSCLIENTSOURCES = \
src/zoidfs/client/bmi_comm.h \
src/zoidfs/client/bmi_comm.c \
src/zoidfs/client/zoidfs_xdr.h \
src/zoidfs/client/zoidfs_xdr.c \
src/zoidfs/client/zoidfsclient.h \
src/zoidfs/client/zoidfsclient.c \
src/zoidfs/client/pzoidfsdef.h

#src_zoidfs_libzoidfsclient_a_LIBADD = \
#    ${top_builddir}/src/zoidfs/libzoidfshints.a

#if HAVE_MPI
#ZOIDFSCLIENTSOURCES += \
#src/zoidfs/client/mpi_comm.h \
#src/zoidfs/client/mpi_comm.c
#endif

if HAVE_MPI
ZOIDFSROUTERSOURCES = \
src/zoidfs/client/pzoidfsdef.h \
src/zoidfs/client/router/zoidfsclientbl.h \
src/zoidfs/client/router/zoidfsclientbl.c \
src/zoidfs/client/router/zoidfsclientss.h \
src/zoidfs/client/router/zoidfsclientss.c \
src/zoidfs/client/router/zoidfsclienthcache.h \
src/zoidfs/client/router/zoidfsclienthcache.c \
src/zoidfs/client/router/zoidfsrouter.h \
src/zoidfs/client/router/zoidfsrouter.c
lib_libiofsloldclientmpi_a_SOURCES += $(ZOIDFSROUTERSOURCES)
endif
lib_libiofslserver_a_SOURCES += $(ZOIDFSCLIENTSOURCES)
lib_libiofsloldclient_a_SOURCES += $(ZOIDFSCLIENTSOURCES)
lib_libiofslclient_a_SOURCES += $(ZOIDFSCLIENTSOURCES)
endif
