if BUILD_IOFWD_CLIENT
lib_LIBRARIES += src/zoidfs/libzoidfsclient.a

src_zoidfs_libzoidfsclient_a_SOURCES = \
src/zoidfs/client/bmi_comm.h \
src/zoidfs/client/bmi_comm.c \
src/zoidfs/client/zoidfs_xdr.h \
src/zoidfs/client/zoidfs_xdr.c \
src/zoidfs/client/zoidfsclient.h \
src/zoidfs/client/zoidfsclient.c

#src_zoidfs_libzoidfsclient_a_LIBADD = \
#    ${top_builddir}/src/zoidfs/libzoidfshints.a

#if HAVE_MPI
#src_zoidfs_libzoidfsclient_a_SOURCES += \
#src/zoidfs/client/mpi_comm.h \
#src/zoidfs/client/mpi_comm.c
#endif

if HAVE_MPI
lib_LIBRARIES += src/zoidfs/libzoidfsrouter.a
src_zoidfs_libzoidfsrouter_a_SOURCES = \
src/zoidfs/client/router/zoidfsclientbl.h \
src/zoidfs/client/router/zoidfsclientbl.c \
src/zoidfs/client/router/zoidfsclientss.h \
src/zoidfs/client/router/zoidfsclientss.c \
src/zoidfs/client/router/zoidfsclienthcache.h \
src/zoidfs/client/router/zoidfsclienthcache.c \
src/zoidfs/client/router/zoidfsrouter.h \
src/zoidfs/client/router/zoidfsrouter.c
endif

endif
