#!/bin/bash

#BUILD THE IOFSL PACKAGE
#=======================

# Execute this script after you have executed the
# directions from the README.git file.
# Make sure to edit "users@yourMachine" to represent
# your proper names.

# We declare CFLAGS so we can find the zoidfs.h files.
# We declare LD_LIBRARY_PATH to indicate where useful libs are.
	
	export CFLAGS=-I/users/rjdamore/iofsl/src/zoidfs 
	export LD_LIBRARY_PATH=$HOME/boost-1.44/lib:$HOME/bmi-2.8.2/lib:$HOME/mpich-install/lib
	git clone ssh://users@yourMachine/~/iofsl

	cd iofsl/	
	./prepare
	mkdir build && cd build

# We need the src files in our build directory:
	
	cp -r ../src .

# Configure with the dependencies you need.  
# bmi and boost are required.  Openpa is needed
# for atomic operation support. If your dependeny
# versions or locations are different edit the 
# following configure command. Remove dependencies 
# that you do not require. (i.e. you may not need mpi).    

	../configure --with-cunit=$HOME/cunit-2.1 --with-bmi=$HOME/bmi-2.8.2 --with-boost=$HOME/boost-1.44 --with-openpa=$HOME/openpa-1.0.2 --with-mpi=$HOME/mpich2-1.3rc1 --prefix=$HOME/iofsl-install --exec-prefix=$HOME/iofsl-install

# Next we make and install.

	make 
	make install

	
