#!/bin/bash

# This script will set up an 
# iofsl.git directory and initialize
# it on your target machine.

# The following will create iofsl.git 
# in your home directory on your target 
# machine. 


mkdir ~/iofsl.git
cd ~/iofsl.git
git init --bare


