
shared_ldadd = src/iofwdevent/libiofwdevent.a \
	       src/iofwdutil/libiofwdutil.a \
	       $(BOOST_UNIT_TEST_FRAMEWORK_LIB) \
	       $(BOOST_DATE_TIME_LIB) \
	       $(BOOST_THREAD_LIB) \
	       $(BOOST_REGEX_LIB) $(AM_LIBS)
shared_ldflags =  $(BOOST_LDFLAGS)

#############################################################################
#  Dummy test case (for debugging)
#############################################################################

check_PROGRAMS += test/boost/dummy
TESTS += test/boost/dummy
test_boost_dummy_SOURCES = test/boost/dummy.cpp \
				  test/boost/ThreadSafety.hh \
				   test/boost/ThreadSafety.cpp

test_boost_dummy_LDFLAGS = $(shared_ldflags)
test_boost_dummy_LDADD = $(shared_ldadd)

#############################################################################
# Resources
#############################################################################
TESTS += test/boost/iofwdevent-resource
check_PROGRAMS += test/boost/iofwdevent-resource
test_boost_iofwdevent_resource_SOURCES = test/boost/dummyresource.cpp \
					 test/boost/singlecompletion.cpp \
				   test/boost/timerresource.cpp \
				   test/boost/tokenresource.cpp \
				   test/boost/bmiresource.cpp \
				   test/boost/ThreadSafety.cpp \
				   test/boost/ThreadSafety.hh \
				   test/boost/iofwdevent-resource.cpp

test_boost_iofwdevent_resource_LDFLAGS = $(shared_ldflags)
test_boost_iofwdevent_resource_LDADD = $(shared_ldadd)

#############################################################################
#  BMI pingpong using resources & threads
#############################################################################

check_PROGRAMS += test/boost/bmi-pingpong
TESTS += test/boost/bmi-pingpong
test_boost_bmi_pingpong_SOURCES = test/boost/bmi-pingpong.cpp \
				  test/boost/ThreadSafety.hh \
				   test/boost/ThreadSafety.cpp

test_boost_bmi_pingpong_LDFLAGS = $(shared_ldflags) @BMI_LDFLAGS@
test_boost_bmi_pingpong_LDADD = $(shared_ldadd)  @BMI_LIBS@



#############################################################################
# Atomics 
#############################################################################
check_PROGRAMS += test/boost/atomics
TESTS += test/boost/atomics
test_boost_atomics_SOURCES = test/boost/atomics.cpp \
				   test/boost/ThreadSafety.hh \
				   test/boost/ThreadSafety.cpp
test_boost_atomics_LDFLAGS = $(shared_ldflags)
test_boost_atomics_LDADD = $(shared_ldadd)

#############################################################################
# Encoder Library
#############################################################################
check_PROGRAMS += test/boost/encoder
TESTS += test/boost/encoder
test_boost_encoder_SOURCES = test/boost/encoder.cpp \
				   test/boost/ThreadSafety.hh \
				   test/boost/ThreadSafety.cpp
test_boost_encoder_LDFLAGS = $(shared_ldflags)
test_boost_encoder_LDADD = $(shared_ldadd)

