
shared_ldadd = src/iofwdevent/libiofwdevent.a \
	       src/iofwdutil/libiofwdutil.a \
	       $(BOOST_UNIT_TEST_FRAMEWORK_LIB) \
	       $(BOOST_THREAD_LIB) \
	       $(BOOST_REGEX_LIB)
shared_ldflags =  $(BOOST_LDFLAGS)

TESTS += test/boost/iofwdevent-resource
check_PROGRAMS += test/boost/iofwdevent-resource
test_boost_iofwdevent_resource_SOURCES = test/boost/timerresource.cpp \
				   test/boost/iofwdevent-resource.cpp \
				   test/boost/bmiresource.cpp \
				   test/boost/singlecompletion.cpp

test_boost_iofwdevent_resource_LDFLAGS = $(shared_ldflags)
test_boost_iofwdevent_resource_LDADD = $(shared_ldadd)

