
SERVERSOURCES += \
   src/iofwd/service/Service.hh \
   src/iofwd/service/Service.cpp \
   src/iofwd/service/ServiceManager.hh \
   src/iofwd/service/ServiceManager.cpp \
   src/iofwd/service/ServiceException.hh

