#!/bin/bash

export CFLAGS=-I$HOME/Documents/workspace/python/iofsl/src/zoidfs

export LD_LIBRARY_PATH=$HOME/opt/mpich2-1.3:$HOME/opt/boost-1.44:$HOME/opt/cunit-2.1:$HOME/opt/bmi-2.8.2
export MPI_INC=-lm

cd $HOME/Documents/workspace/python/iofsl/

make install