lib_LIBRARIES += src/zoidfs/libzoidfs.a

src_zoidfs_libzoidfs_a_CPPFLAGS = $(AM_CPPFLAGS)
src_zoidfs_libzoidfs_a_CFLAGS = $(AM_CFLAGS)

src_zoidfs_libzoidfs_a_SOURCES = \
src/zoidfs/dispatcher/zint-handler.h \
src/zoidfs/dispatcher/zint-handler.c \
src/zoidfs/dispatcher/zoidfs.c

# local is always included
src_zoidfs_libzoidfs_a_SOURCES += \
src/zoidfs/dispatcher/local/zoidfs-local.h \
src/zoidfs/dispatcher/local/zoidfs-local.c

if DISPATCH_PVFS
src_zoidfs_libzoidfs_a_CPPFLAGS += @PVFS2_CPPFLAGS@
src_zoidfs_libzoidfs_a_CFLAGS += @PVFS2_CFLAGS@
src_zoidfs_libzoidfs_a_SOURCES += \
src/zoidfs/dispatcher/pvfs/zoidfs-pvfs2.c \
src/zoidfs/dispatcher/pvfs/zoidfs-pvfs2.h
endif

if DISPATCH_LIBSYSIO
   # TODO: move these defines into @ SYSIO_xxxx @ 
src_zoidfs_libzoidfs_a_CPPFLAGS += @SYSIO_CPPFLAGS@
src_zoidfs_libzoidfs_a_CFLAGS += @SYSIO_CFLAGS@
src_zoidfs_libzoidfs_a_SOURCES += \
src/zoidfs/dispatcher/sysio/zoidfs-sysio.h \
src/zoidfs/dispatcher/sysio/zoidfs-sysio.c
endif

if DISPATCH_POSIX
src_zoidfs_libzoidfs_a_SOURCES += \
src/zoidfs/dispatcher/posix/dcache.c \
src/zoidfs/dispatcher/posix/fcache.c \
src/zoidfs/dispatcher/posix/zoidfs-posix.c \
src/zoidfs/dispatcher/posix/zoidfs-util.c \
src/zoidfs/dispatcher/posix/dcache.h \
src/zoidfs/dispatcher/posix/fcache.h \
src/zoidfs/dispatcher/posix/zoidfs-posix.h \
src/zoidfs/dispatcher/posix/zoidfs-util.h 
endif

