
nobase_include_HEADERS +=  \
  src/zoidfs/dispatcher/zint-handler.h \
  src/zoidfs/dispatcher/local/zoidfs-local.h \
  src/zoidfs/dispatcher/pvfs/zoidfs-pvfs2.h \
  src/zoidfs/dispatcher/sysio/zoidfs-sysio.h \
  src/zoidfs/dispatcher/posix/dcache.h \
  src/zoidfs/dispatcher/posix/fcache.h \
  src/zoidfs/dispatcher/posix/zoidfs-posix.h \
  src/zoidfs/dispatcher/posix/zoidfs-util.h \
  src/zoidfs/dispatcher/nofs/zoidfs-nofs.h \
  src/zoidfs/dispatcher/gridftp/zoidfs-gridftp.h


DISPATCHERSOURCES = \
src/zoidfs/dispatcher/zint-handler.h \
src/zoidfs/dispatcher/zint-handler.c \
src/zoidfs/dispatcher/zoidfs.c

# local is always included
DISPATCHERSOURCES += \
src/zoidfs/dispatcher/local/zoidfs-local.h \
src/zoidfs/dispatcher/local/zoidfs-local.c

if DISPATCH_PVFS
DISPATCHERSOURCES += \
src/zoidfs/dispatcher/pvfs/zoidfs-pvfs2.c \
src/zoidfs/dispatcher/pvfs/zoidfs-pvfs2.h
endif

if DISPATCH_LIBSYSIO
DISPATCHERSOURCES += \
src/zoidfs/dispatcher/sysio/zoidfs-sysio.h \
src/zoidfs/dispatcher/sysio/zoidfs-sysio.c
endif

if DISPATCH_POSIX
DISPATCHERSOURCES += \
src/zoidfs/dispatcher/posix/dcache.c \
src/zoidfs/dispatcher/posix/fcache.c \
src/zoidfs/dispatcher/posix/zoidfs-posix.c \
src/zoidfs/dispatcher/posix/zoidfs-util.c \
src/zoidfs/dispatcher/posix/dcache.h \
src/zoidfs/dispatcher/posix/fcache.h \
src/zoidfs/dispatcher/posix/zoidfs-posix.h \
src/zoidfs/dispatcher/posix/zoidfs-util.h 
endif

if DISPATCH_NOFS
DISPATCHERSOURCES += \
src/zoidfs/dispatcher/nofs/zoidfs-nofs.h \
src/zoidfs/dispatcher/nofs/zoidfs-nofs.c
endif

if DISPATCH_GRIDFTP
DISPATCHERSOURCES += \
src/zoidfs/dispatcher/gridftp/zoidfs-gridftp.h \
src/zoidfs/dispatcher/gridftp/zoidfs-gridftp.c
endif

if DISPATCH_ROSS
src_zoidfs_libzoidfs_a_SOURCES += \
src/zoidfs/dispatcher/ross/zoidfs-ross.h \
src/zoidfs/dispatcher/ross/zoidfs-ross.c
endif

lib_libiofslcommon_a_SOURCES += $(DISPATCHERSOURCES)
lib_libiofsloldclientlocal_a_SOURCES += $(DISPATCHERSOURCES)

