#ifndef ZOIDFS_CLIENT_ROUTER_ZOIDFSCLIENTBL_H
#define ZOIDFS_CLIENT_ROUTER_ZOIDFSCLIENTBL_H

extern zoidfs_router_t zoidfs_router_simple_block_layout_server;

#endif /* ZOIDFS_CLIENT_ROUTER_ZOIDFSCLIENTBL_H */
