CPPCLIENTLIB += \
    src/iofwdclient/iofwdclient-fwd.hh \
    src/iofwdclient/IOFWDRequest.hh \
    src/iofwdclient/IOFWDRequest.cpp \
    src/iofwdclient/RequestTracker.hh \
    src/iofwdclient/RequestTracker.cpp \
    src/iofwdclient/IOFWDClientCB.hh \
    src/iofwdclient/IOFWDClient.hh \
    src/iofwdclient/IOFWDClient.cpp \
    src/iofwdclient/SyncClient.hh \
    src/iofwdclient/SyncClient.cpp \
    src/iofwdclient/CBClient.hh \
    src/iofwdclient/CBClient.cpp \
    src/iofwdclient/ASClient.hh \
    src/iofwdclient/ASClient.cpp \
    src/iofwdclient/ScopedRequest.hh \
    src/iofwdclient/CommStream.hh \
    src/iofwdclient/CommStream.cpp \
    src/iofwdclient/PollQueue.hh \
    src/iofwdclient/PollQueue.cpp \
    src/iofwdclient/FakeBlocker.hh \
    \
    src/iofwdclient/clientsm/BMIServerHelper.hh \
    src/iofwdclient/clientsm/BMIServerSM.hh \
    src/iofwdclient/clientsm/RPCServerHelper.hh \
    src/iofwdclient/clientsm/RPCServerSM.hh \
    src/iofwdclient/clientsm/GetAttrClientSM.hh \
    src/iofwdclient/clientsm/GetAttrClientSM.cpp \
    src/iofwdclient/clientsm/CreateClientSM.hh \
    src/iofwdclient/clientsm/CreateClientSM.cpp \
    src/iofwdclient/clientsm/LookupClientSM.hh \
    src/iofwdclient/clientsm/LookupClientSM.cpp \
    src/iofwdclient/clientsm/RPCCommClientSM.hh \
    src/iofwdclient/streamwrappers/LookupStreams.hh \
    src/iofwdclient/streamwrappers/GetAttrInStream.hh \
    src/iofwdclient/streamwrappers/GetAttrOutStream.hh \
    src/iofwdclient/iofwdclientlib.hh \
    src/iofwdclient/LinkHelper.hh \
    src/iofwdclient/LinkHelper.cpp \
    src/iofwdclient/IOFWDClient.cpp \
    src/iofwdclient/IOFWDClient.hh \
    src/iofwdclient/CommStream.hh \
    src/iofwdclient/CommStream.cpp

#    src/iofwdclient/iofwdclientlib.hh 
#    
#    src/iofwdclient/directclient/LookupStream.hh \
#    src/iofwdclient/directclient/LookupStream.cpp \
#    src/iofwdclient/directclient/IOFWDClient.hh \
#    src/iofwdclient/directclient/IOFWDClient.cpp \
#    src/iofwdclient/directclient/RPCCommClass.cpp \
#    src/iofwdclient/directclient/RPCCommClass.hh 

#    src/iofwdclient/streamwrappers/GetAttrInStream.hh \
#    src/iofwdclient/streamwrappers/GetAttrOutStream.hh 

#
# It is OK to define this here, even if we add sources to CLIENTLIB later on;
# The expression is not evaluated at this point.
#
lib_LIBRARIES += src/iofwdclient/libiofwdclient.a
src_iofwdclient_libiofwdclient_a_SOURCES = $(CPPCLIENTLIB)

