nobase_include_HEADERS +=  \
    src/iofwdclient/iofwdclient-fwd.hh \
    src/iofwdclient/IOFWDRequest.hh \
    src/iofwdclient/RequestTracker.hh \
    src/iofwdclient/IOFWDClientCB.hh \
    src/iofwdclient/SyncClient.hh \
    src/iofwdclient/CBClient.hh \
    src/iofwdclient/ASClient.hh \
    src/iofwdclient/ScopedRequest.hh \
    src/iofwdclient/PollQueue.hh \
    src/iofwdclient/FakeBlocker.hh \
    src/iofwdclient/clientsm/BMIServerHelper.hh \
    src/iofwdclient/clientsm/BMIServerSM.hh \
    src/iofwdclient/clientsm/RPCServerHelper.hh \
    src/iofwdclient/clientsm/RPCServerSM.hh \
    src/iofwdclient/clientsm/GetAttrClientSM.hh \
    src/iofwdclient/clientsm/CreateClientSM.hh \
    src/iofwdclient/clientsm/LookupClientSM.hh \
    src/iofwdclient/clientsm/WriteClientSM.hh \
    src/iofwdclient/clientsm/RPCClientRead.hh \
    src/iofwdclient/clientsm/RPCCommClientSM.hh \
    src/iofwdclient/clientsm/CommitClientSM.hh \
    src/iofwdclient/clientsm/MkdirClientSM.hh \
    src/iofwdclient/clientsm/SetAttrClientSM.hh \
    src/iofwdclient/clientsm/ReadLinkClientSM.hh \
    src/iofwdclient/clientsm/ReadDirClientSM.hh \
    src/iofwdclient/clientsm/SymLinkClientSM.hh \
    src/iofwdclient/clientsm/LinkClientSM.hh \
    src/iofwdclient/clientsm/RenameClientSM.hh \
    src/iofwdclient/clientsm/RemoveClientSM.hh \
    src/iofwdclient/LinkHelper.hh \
    src/iofwdclient/IOFWDClient.hh \
    src/iofwdclient/CommStream.hh \
    src/iofwdclient/clientsm/RPCClientWrite.hh \
    src/iofwdclient/clientsm/RPCCommWriteSM.hh \
    src/iofwdclient/clientsm/RPCCommReadSM.hh \
    src/iofwdclient/clientsm/ReadClientSM.hh \
    src/iofwdclient/streamwrappers/ZoidFSStreamWrappers.hh \
    src/iofwdclient/streamwrappers/GetAttrStreams.hh 

CPPCLIENTLIB += \
    src/iofwdclient/iofwdclient-fwd.hh \
    src/iofwdclient/IOFWDRequest.hh \
    src/iofwdclient/IOFWDRequest.cpp \
    src/iofwdclient/RequestTracker.hh \
    src/iofwdclient/RequestTracker.cpp \
    src/iofwdclient/IOFWDClientCB.hh \
    src/iofwdclient/IOFWDClient.hh \
    src/iofwdclient/IOFWDClient.cpp \
    src/iofwdclient/SyncClient.hh \
    src/iofwdclient/SyncClient.cpp \
    src/iofwdclient/CBClient.hh \
    src/iofwdclient/CBClient.cpp \
    src/iofwdclient/ASClient.hh \
    src/iofwdclient/ASClient.cpp \
    src/iofwdclient/ScopedRequest.hh \
    src/iofwdclient/CommStream.hh \
    src/iofwdclient/CommStream.cpp \
    src/iofwdclient/PollQueue.hh \
    src/iofwdclient/PollQueue.cpp \
    src/iofwdclient/FakeBlocker.hh \
    \
    src/iofwdclient/clientsm/BMIServerHelper.hh \
    src/iofwdclient/clientsm/BMIServerSM.hh \
    src/iofwdclient/clientsm/RPCServerHelper.hh \
    src/iofwdclient/clientsm/RPCServerSM.hh \
    src/iofwdclient/clientsm/GetAttrClientSM.hh \
    src/iofwdclient/clientsm/GetAttrClientSM.cpp \
    src/iofwdclient/clientsm/CreateClientSM.hh \
    src/iofwdclient/clientsm/CreateClientSM.cpp \
    src/iofwdclient/clientsm/LookupClientSM.hh \
    src/iofwdclient/clientsm/LookupClientSM.cpp \
    src/iofwdclient/clientsm/WriteClientSM.hh \
    src/iofwdclient/clientsm/WriteClientSM.cpp \
    src/iofwdclient/clientsm/RPCClientRead.hh \
    src/iofwdclient/clientsm/RPCCommClientSM.hh \
    src/iofwdclient/clientsm/CommitClientSM.hh \
    src/iofwdclient/clientsm/CommitClientSM.cpp \
    src/iofwdclient/clientsm/MkdirClientSM.hh \
    src/iofwdclient/clientsm/MkdirClientSM.cpp \
    src/iofwdclient/clientsm/SetAttrClientSM.hh \
    src/iofwdclient/clientsm/SetAttrClientSM.cpp \
    src/iofwdclient/clientsm/ReadLinkClientSM.hh \
    src/iofwdclient/clientsm/ReadLinkClientSM.cpp \
    src/iofwdclient/clientsm/ReadDirClientSM.hh \
    src/iofwdclient/clientsm/ReadDirClientSM.cpp \
    src/iofwdclient/clientsm/SymLinkClientSM.hh \
    src/iofwdclient/clientsm/SymLinkClientSM.cpp \
    src/iofwdclient/clientsm/LinkClientSM.hh \
    src/iofwdclient/clientsm/LinkClientSM.cpp \
    src/iofwdclient/clientsm/RenameClientSM.hh \
    src/iofwdclient/clientsm/RenameClientSM.cpp \
    src/iofwdclient/clientsm/RemoveClientSM.hh \
    src/iofwdclient/clientsm/RemoveClientSM.cpp \
    src/iofwdclient/LinkHelper.hh \
    src/iofwdclient/LinkHelper.cpp \
    src/iofwdclient/IOFWDClient.cpp \
    src/iofwdclient/IOFWDClient.hh \
    src/iofwdclient/CommStream.hh \
    src/iofwdclient/CommStream.cpp \
    src/iofwdclient/clientsm/RPCClientWrite.hh \
    src/iofwdclient/clientsm/RPCCommWriteSM.hh \
    src/iofwdclient/clientsm/RPCCommReadSM.hh \
    src/iofwdclient/clientsm/ReadClientSM.hh \
    src/iofwdclient/clientsm/ReadClientSM.cpp \
    src/iofwdclient/streamwrappers/ZoidFSStreamWrappers.hh \
    src/iofwdclient/streamwrappers/GetAttrStreams.hh \
    \
    src/iofwdclient/zoidfsclient-cwrappers.c


#    src/iofwdclient/iofwdclientlib.hh 
#    
#    src/iofwdclient/directclient/LookupStream.hh \
#    src/iofwdclient/directclient/LookupStream.cpp \
#    src/iofwdclient/directclient/IOFWDClient.hh \
#    src/iofwdclient/directclient/IOFWDClient.cpp \
#    src/iofwdclient/directclient/RPCCommClass.cpp \
#    src/iofwdclient/directclient/RPCCommClass.hh 

#    src/iofwdclient/streamwrappers/GetAttrInStream.hh \
#    src/iofwdclient/streamwrappers/GetAttrOutStream.hh 

#
# It is OK to define this here, even if we add sources to CLIENTLIB later on;
# The expression is not evaluated at this point.
#
#lib_LIBRARIES += src/iofwdclient/libiofwdclient.a
lib_libiofslclient_a_SOURCES += $(CPPCLIENTLIB)

