# empty

include_HEADERS = src/zoidfs/zoidfs.h \
                  src/zoidfs/hints/zoidfs-hints.h

noinst_HEADERS += \
		 src/zoidfs/zoidfs-comm.h \
		 src/zoidfs/zoidfs-proto.h


include $(top_srcdir)/src/zoidfs/hints/Makefile.subdir
include $(top_srcdir)/src/zoidfs/util/Makefile.subdir
include $(top_srcdir)/src/zoidfs/dispatcher/Makefile.subdir
include $(top_srcdir)/src/zoidfs/client/Makefile.subdir
include $(top_srcdir)/src/zoidfs/profiler/Makefile.subdir

