
# generic frontend interface
SERVERSOURCES+= \
src/iofwd/frontend/Frontend.cpp \
src/iofwd/frontend/Frontend.hh

include src/iofwd/frontend/bmi/Makefile.subdir

include src/iofwd/frontend/rpc/Makefile.subdir

if DISPATCH_ROSS
include src/iofwd/frontend/ross/Makefile.subdir
endif

