if BUILD_IOFWD_CLIENT
noinst_LIBRARIES += src/client/libiofwdclient.a

src_client_libiofwdclient_a_LIBLDFLAGS = \
    @BOOST_LDFLAGS@ \
    @BOOST_PROGRAM_OPTIONS_LIB@ \
    @BOOST_DATE_TIME_LIB@ \
    @BOOST_THREAD_LIB@ \
    @BOOST_REGEX_LIB@

src_client_libiofwdclient_a_SOURCES = \
src/client/CommChannel.cpp \
src/client/CommChannel.hh \
src/client/IOFWDClient.cpp \
src/client/IOFWDClient.hh
endif
